#!/bin/bash
#SBATCH -J CRTM
#SBATCH -n 16
#SBATCH -N 1
#SBATCH -p development
#SBATCH -t 2:00:00
#SBATCH -o out_crtm
#SBATCH -e error_crtm

#export OMP_NUM_THREADS=4
# #export MPSTKZ=2T
# #export MP_STACK_SLAVESIZE=2T
# #export OMP_STACKSIZE=2T

ibrun ./crtm.exe

